language: scala
dist: trusty
sudo: false
scala:
  - 2.12.4
jdk:
  - openjdk8

cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/boot/scala-$TRAVIS_SCALA_VERSION

branches:
  only:
    - master
    - testing
    - dev

env:
  global:
    - AWS_DEFAULT_REGION=eu-west-1

install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin

script:
  - sbt clean
  - sbt ++$TRAVIS_SCALA_VERSION compile
  - sbt ++$TRAVIS_SCALA_VERSION test:compile
  - sbt ++$TRAVIS_SCALA_VERSION "project hat" coverage test -Dconfig.file=hat/conf/application.test.conf

after_success:
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
  - |
    if [[ "$TRAVIS_PULL_REQUEST" = "false" || -z "$RUMPEL" ]]; then
      sbt coverageReport
    fi

deploy:
  - provider: script
    script:
      - sbt publish
    skip_cleanup: true
