language: scala
dist: trusty
sudo: false
scala:
- 2.12.12
jdk:
- openjdk8
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/boot/scala-$TRAVIS_SCALA_VERSION"
branches:
  only:
  - master
  - dev
env:
  global:
  - AWS_DEFAULT_REGION=eu-west-1
  - AWS_REGION=eu-west-1
  - secure: rRmQJ0h03w/+Q71R8tLsBq+KZsKaJLdwnxwEqwyFvefzqXxAlbXwtfbOpjaQT1sclYUprVwdZ9glf5tam8nk8UJTjNDy8ohnvxB2/Ow0oMhhvulKTtE+bGeKyWhkWonxMVYonCfj32OE5LX0cjcTiHp1mQhXBBHrO5J6wS8NFES40CImJEHljx9AbGxIfLg79B4+8fj6Dz2mNnA136NO3aP1YjZDuysuF0MKPavqsGYKkgE3C+YnKRo4cCNiODyunHr55zkrOVFLgDWJ8Ia833JiZyxZaAzSDDZnLkMXBxt+JvgM6XRtNE3hdYJ5PZYEXZcsRhoxXgZMHgsl5vpCq/f2cZiXeo3vX5WPgjTeC8eEpUt51t0y9uJB8zWIDzKXa2MjDzjYnKlfdInJqzpDaMGHy9MfganVqPsIh9CuRzNlhaJmXtmlqr132B/gBxSlgbv6Qw1YOmecW6u+xNTLKkqDIFHx9e6UeQHKAnvasaRa8KH1j/ZDI0zDuPXrC+rkUx2uO8JKoQWNa5dWoJwvcSaCiSsl9mgPK492OuuSS8y5XR//2oRieAPObWEUkNzBejSbkntVhFmRQ/ht3tVbnbcy2nszQsgSCENnIDTK4CXiaQl+sFIlgQPu60RbGoCaDQtuaA1cnEiUjj6c6WYKQIO08zctt/83MWp1eJrPhbo=
  - secure: hDYa/9qlkF0WrkOuZ8gl9M6+CPBwvHsGi+Ryzh7zEuYmUwlRRKyqyIo8XoxNwvpE/VDPAVvipryhZFBjFXCd0WAE+H9NZlTvFTPYGUEDzp3hsHcNt+ekdX/uZNKaE6fQqtJ3OVj3/mr0uvcFxEEnweRrwxsaM+HMbu8WtMllGJCKHCadiOJHw8iKte2wvGsvdG8EcFUEAMtKbmlkNi77gnN580p+jNDgM6jjgxefilR5Qmr78+loFaBNadQsdqnD0mMrjoNhuuo8NQxvJU9AAOB4wOH19kdWdyGzw4ksjP0Sp9T/cOrORV6Rtzm6CtTRatvOKo8neDE5BgWFTj9P+6gWvkxpEkih/har0rep7C999QMazLjEXx2EbcIe7yTfkmQ7c4E6jbJoIJMCAXD+tZCdhwiT1aODzyak1eMzpDWpAMgdt+w1BTMy3WEiTHBoMy1QwDMbSWAS1xGkzF2oixa/q8tv18Yn0CwITRGDFDvu53My/t0VO6wTolCoii4f/ym4irU3sopzRLTMdjYz4E5YqfPX6pr3agQvIWWu7rEarAJDCECLAhyP1+jZrHbnuGhGL5zKLm+LOq3A1hHRf12j6sllwMquIYwzgY6k3lDElSgEvpvNwj92G3obGF63cU3nFmmNsM5skTSzDz+uFvAFxguuqDLSWDkF7AKT50I=
install:
- pip install --user awscli
- export PATH=$PATH:$HOME/.local/bin
script:
- sbt clean
- sbt ++$TRAVIS_SCALA_VERSION compile
- sbt ++$TRAVIS_SCALA_VERSION test:compile
- sbt ++$TRAVIS_SCALA_VERSION coverage test
- sbt driver/it:test
after_success:
- find $HOME/.sbt -name "*.lock" | xargs rm
- find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
- |
  if [[ "$TRAVIS_PULL_REQUEST" = "false" || -z "$RUMPEL" ]]; then
    sbt coverageReport
  fi
deploy:
- provider: script
  script:
  - sbt publish
  skip_cleanup: true
