name: CI

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main
    
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup
        uses: actions/setup-java@v1
        with:
          java-version: 11
          java-package: jdk
          architecture: x64

      - name: Run Scala 2.12 tests
        run: sbt clean compile test it:test

      - name: Run Scala 2.13 integration tests
        run: sbt "++ 2.13.4 clean;driver/it:test"
